"""Add moderation fields

Revision ID: ed553efa9f60
Revises: 
Create Date: 2025-03-16 01:29:23.680478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed553efa9f60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('moderation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('moderated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_selected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_history', schema=None) as batch_op:
        batch_op.drop_column('is_selected')
        batch_op.drop_column('moderated_at')
        batch_op.drop_column('moderation_notes')
        batch_op.drop_column('moderation_status')

    # ### end Alembic commands ###
